export const GET_CUSTOM_ITINERARY_REQUEST = 'GET_CUSTOM_ITINERARY_REQUEST';
export const GET_CUSTOM_ITINERARY_SUCCESS = 'GET_CUSTOM_ITINERARY_SUCCESS';
export const GET_CUSTOM_ITINERARY_FAIL = 'GET_CUSTOM_ITINERARY_FAIL';

export const ADD_ITINERARY_SECTION_REQUEST = 'ADD_ITINERARY_SECTION_REQUEST';
export const ADD_ITINERARY_SECTION_SUCCESS = 'ADD_ITINERARY_SECTION_SUCCESS';
export const ADD_ITINERARY_SECTION_FAIL = 'ADD_ITINERARY_SECTION_FAIL';

export const ADD_ITINERARY_DAY_REQUEST = 'ADD_ITINERARY_DAY_REQUEST';
export const ADD_ITINERARY_DAY_SUCCESS = 'ADD_ITINERARY_DAY_SUCCESS';
export const ADD_ITINERARY_DAY_FAIL = 'ADD_ITINERARY_DAY_FAIL';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';