export const GET_CUSTOM_ITINERARY_REQUEST = 'GET_CUSTOM_ITINERARY_REQUEST';
export const GET_CUSTOM_ITINERARY_SUCCESS = 'GET_CUSTOM_ITINERARY_SUCCESS';
export const GET_CUSTOM_ITINERARY_FAIL = 'GET_CUSTOM_ITINERARY_FAIL';