export const FIXEDITINERARY_LIST_REQUEST = 'FIXEDITINERARY_LIST_REQUEST';
export const FIXEDITINERARY_LIST_SUCCESS = 'FIXEDITINERARY_LIST_SUCCESS';
export const FIXEDITINERARY_LIST_FAIL = 'FIXEDITINERARY_LIST_FAIL';

export const ITINERARY_PRICE_REQUEST = 'ITINERARY_PRICE_REQUEST';
export const ITINERARY_PRICE_SUCCESS = 'ITINERARY_PRICE_SUCCESS';
export const ITINERARY_PRICE_FAIL = 'ITINERARY_PRICE_FAIL';