export const FIXEDITINERARY_LIST_REQUEST = 'FIXEDITINERARY_LIST_REQUEST';
export const FIXEDITINERARY_LIST_SUCCESS = 'FIXEDITINERARY_LIST_SUCCESS';
export const FIXEDITINERARY_LIST_FAIL = 'FIXEDITINERARY_LIST_FAIL';

export const GET_FIXED_ITINERARY_REQUEST = 'GET_FIXED_ITINERARY_REQUEST';
export const GET_FIXED_ITINERARY_SUCCESS = 'GET_FIXED_ITINERARY_SUCCESS';
export const GET_FIXED_ITINERARY_FAIL = 'GET_FIXED_ITINERARY_FAIL';

export const FIXED_ITINERARY_SAVE_REQUEST = 'FIXED_ITINERARY_SAVE_REQUEST';
export const FIXED_ITINERARY_SAVE_SUCCESS = 'FIXED_ITINERARY_SAVE_SUCCESS';
export const FIXED_ITINERARY_SAVE_FAIL = 'FIXED_ITINERARY_SAVE_FAIL';

export const ITINERARY_PRICE_REQUEST = 'ITINERARY_PRICE_REQUEST';
export const ITINERARY_PRICE_SUCCESS = 'ITINERARY_PRICE_SUCCESS';
export const ITINERARY_PRICE_FAIL = 'ITINERARY_PRICE_FAIL';

export const SAVE_CONTENT_REQUEST = 'SAVE_CONTENT_REQUEST';
export const SAVE_CONTENT_SUCCESS = 'SAVE_CONTENT_SUCCESS';
export const SAVE_CONTENT_FAIL = 'SAVE_CONTENT_FAIL';