export const FIXEDITINERARY_LIST_REQUEST = 'FIXEDITINERARY_LIST_REQUEST';
export const FIXEDITINERARY_LIST_SUCCESS = 'FIXEDITINERARY_LIST_SUCCESS';
export const FIXEDITINERARY_LIST_FAIL = 'FIXEDITINERARY_LIST_FAIL';