export const LOCALS_LIST_REQUEST = 'LOCALS_LIST_REQUEST';
export const LOCALS_LIST_SUCCESS = 'LOCALS_LIST_SUCCESS';
export const LOCALS_LIST_FAIL = 'LOCALS_LIST_FAIL';

export const SAVED_LOCALS_LIST_SUCCESS = 'SAVED_LOCALS_LIST_SUCCESS'
export const SAVED_LOCALS_LIST_FAIL = 'SAVED_LOCALS_LIST_FAIL'