export const LOCATION_LIST_REQUEST = 'LOCATION_LIST_REQUEST';
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS';
export const LOCATION_LIST_FAIL = 'LOCATION_LIST_FAIL';

export const POPULAR_LOCATION_LIST_REQUEST = 'POPULAR_LOCATION_LIST_REQUEST';
export const POPULAR_LOCATION_LIST_SUCCESS = 'POPULAR_LOCATION_LIST_SUCCESS';
export const POPULAR_LOCATION_LIST_FAIL = 'POPULAR_LOCATION_LIST_FAIL';

export const NEWEST_LOCATION_LIST_REQUEST = 'NEWEST_LOCATION_LIST_REQUEST';
export const NEWEST_LOCATION_LIST_SUCCESS = 'NEWEST_LOCATION_LIST_SUCCESS';
export const NEWEST_LOCATION_LIST_FAIL = 'NEWEST_LOCATION_LIST_FAIL';

export const LOCATION_DETAILS_REQUEST = 'LOCATION_DETAILS_REQUEST';
export const LOCATION_DETAILS_SUCCESS = 'LOCATION_DETAILS_SUCCESS';
export const LOCATION_DETAILS_FAIL = 'LOCATION_DETAILS_FAIL';

export const SAVED_LOCATION_LIST_SUCCESS = 'SAVED_LOCATION_LIST_SUCCESS'
export const SAVED_LOCATION_LIST_FAIL = 'SAVED_LOCATION_LIST_FAIL'