export const SAVE_ENTITY_REQUEST = 'SAVE_ENTITY_REQUEST'
export const SAVE_ENTITY_SUCCESS = 'SAVE_ENTITY_SUCCESS'
export const SAVE_ENTITY_FAIL = 'SAVE_ENTITY_FAIL'

export const REMOVE_ENTITY_REQUEST = 'REMOVE_ENTITY_REQUEST'
export const REMOVE_ENTITY_SUCCESS = 'REMOVE_ENTITY_SUCCESS'
export const REMOVE_ENTITY_FAIL = 'REMOVE_ENTITY_FAIL'