export const TRAVELEXPERTS_LIST_REQUEST = 'TRAVELEXPERTS_LIST_REQUEST';
export const TRAVELEXPERTS_LIST_SUCCESS = 'TRAVELEXPERTS_LIST_SUCCESS';
export const TRAVELEXPERTS_LIST_FAIL = 'TRAVELEXPERTS_LIST_FAIL';

export const SAVED_TRAVELEXPERTS_LIST_SUCCESS = 'SAVED_TRAVELEXPERTS_LIST_SUCCESS'
export const SAVED_TRAVELEXPERTS_LIST_FAIL = 'SAVED_TRAVELEXPERTS_LIST_FAIL'