export const TRAVELEXPERTS_LIST_REQUEST = 'TRAVELEXPERTS_LIST_REQUEST';
export const TRAVELEXPERTS_LIST_SUCCESS = 'TRAVELEXPERTS_LIST_SUCCESS';
export const TRAVELEXPERTS_LIST_FAIL = 'TRAVELEXPERTS_LIST_FAIL';

export const GET_TRAVEL_EXPERT_REQUEST = 'GET_TRAVEL_EXPERT_REQUEST';
export const GET_TRAVEL_EXPERT_SUCCESS = 'GET_TRAVEL_EXPERT_SUCCESS';
export const GET_TRAVEL_EXPERT_FAIL = 'GET_TRAVEL_EXPERT_FAIL';

export const SAVED_TRAVELEXPERTS_LIST_SUCCESS = 'SAVED_TRAVELEXPERTS_LIST_SUCCESS'
export const SAVED_TRAVELEXPERTS_LIST_FAIL = 'SAVED_TRAVELEXPERTS_LIST_FAIL'